### ISSUE TITLE
Unable to auto approve

### ISSUE THREAD

**Issue by sudhirkumar05** [peter-evans/enable-pull-request-automerge#1059]
I am unable to auto approve the PR as i get error `failed to create review: Message: Can not approve your own pull request`

```
jobs:
  otel-collector-patching:
    runs-on: [xyz]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Find latest version
        id: script
        run: |
          source test.sh
      - name: Create Pull Request
        id: automerge
        uses: peter-evans/create-pull-request@v5
        with:
          token: "${{ secrets.GITHUB_TOKEN }}" # Require token to run this PR
          author: "sdk[bot] <120429439+sdk-renovate[bot]@users.noreply.github.com>"
          branch: abcd-${{ env.branch_name }}
          delete-branch: true
          base: main
          commit-message: Latest version
          title: Latest version
          body: |
            Weekly checked
              - bla bla
              - bla bla
      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto "${{ steps.automerge.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto approve
        run: gh pr review --approve "${{ steps.automerge.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
All the steps works fine except the auto approve one. This returns `Can not approve your own pull request`
