### ISSUE TITLE
Branch is not deleted

### ISSUE THREAD

**Issue by carstencodes** [peter-evans/enable-pull-request-automerge#1061]
During pull request setup, the delete-branch method was set to true.

Received:

```shell
Unexpected input(s) 'delete-branch', valid inputs are ['token', 'repository', 'pull-request-number', 'merge-method']
```

Configuration:

```yaml
Run peter-evans/enable-pull-request-automerge@v3
----
  with:
    token: ***
    pull-request-number: 147
    merge-method: rebase
    delete-branch: true
    repository: carstencodes/pdm-bump
  env:
    pdm_version: 2.8.2
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/carstencodes/pdm-bump/actions/runs/5742218024/job/15563903769#step:15:3).11.[4](https://github.com/carstencodes/pdm-bump/actions/runs/5742218024/job/15563903769#step:15:4)/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.4/x64/lib:/opt/hostedtoolcache/Python/3.11.2/x64/lib
    PYTHONPATH: /home/runner/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/pep[5](https://github.com/carstencodes/pdm-bump/actions/runs/5742218024/job/15563903769#step:15:5)82
    LD_PRELOAD: /lib/x8[6](https://github.com/carstencodes/pdm-bump/actions/runs/5742218024/job/15563903769#step:15:6)_64-linux-gnu/libgcc_s.so.1
    PDM_UPDATE_OUTPUT: 🔒 Lock successful Packages to update: - chardet 5.1.0 -> 5.2.0 - rich 13.5.1 -> 13.5.2
    PDM_PACKAGES_TO_UPDATE: Packages to update:
    - chardet 5.1.0 -> 5.2.0
    - rich 13.5.1 -> 13.5.2
    PDM_UPDATED_PACKAGES_NAMES:   - chardet 5.1.0 -> 5.2.0
    - rich 13.5.1 -> 13.5.2
    PDM_NUMBER_OF_NEW_PACKAGES: 2
    GIT_PDM_TITLE: chore: Updated 2 dependencies in pdm.lock
    PULL_REQUEST_NUMBER: 147
```
[Example pipeline with complete log](https://github.com/carstencodes/pdm-bump/actions/runs/5742218024/job/15563903769)
