### ISSUE TITLE
Auto merge fails with node warnings

### ISSUE THREAD

**Issue by N6REJ** [peter-evans/enable-pull-request-automerge#1103]
@peter-evans I'm sorry to bother you again, I'm a noob and trying my best.
I read thru your response and got the CPR working just fine ( TY! ) and it creates a pr  now but the auto merge just doesn't merge.
I tried the GH version and it complained there was no pr number
PLEASE help.

output: https://github.com/Bearsampp/Bearsampp/actions/runs/10051005432
action:  https://github.com/Bearsampp/Bearsampp/blob/main/.github/workflows/combine_releases.yml
python script: https://github.com/Bearsampp/Bearsampp/blob/main/.github/combine_releases.py

**Comment by peter-evans** [comment]
Hi @N6REJ 

You need to give the step an `id`, otherwise it can't reference the output in the next step.

```diff
            -   name: Create Pull Request
+               id: cpr
                uses: peter-evans/create-pull-request@v6
                with:
                    token: ${{ secrets.GH_ACTIONS }}
                    branch: update-releases
                    base: main
                    title: 'Update combined releases JSON'
                    body: 'This PR updates the combined releases JSON file.'
                    commit-message: 'Update combined releases JSON'
                    delete-branch: true

            -   name: Enable Pull Request Automerge
                if: steps.cpr.outputs.pull-request-operation == 'created'
                uses: peter-evans/enable-pull-request-automerge@v3
                with:
                    token: ${{ secrets.GH_ACTIONS }}
                    pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
                    merge-method: merge
```

**Comment by N6REJ** [comment]
I had forgotten to add the auto approve step and it said 
"1s
Run gh pr review --approve "406"
failed to create review: GraphQL: Can not approve your own pull request (addPullRequestReview)
Error: Process completed with exit code [1](https://github.com/Bearsampp/Bearsampp/actions/runs/10056177432/job/27794436146#step:8:1)."

**Comment by N6REJ** [comment]
Thanks to all your help I was able to get it as you were writing that.  I hope this helps someone else...
```
            -   name: Create Pull Request
                id: cpr
                uses: peter-evans/create-pull-request@v6
                with:
                    token: ${{ secrets.GH_PAT }}
                    author: Bearsampp <support@bearsampp.com>
                    branch: update-releases
                    base: main
                    title: 'Update combined releases JSON'
                    body: 'This PR updates the combined releases JSON file.'
                    commit-message: 'Update combined releases JSON'
                    delete-branch: true

            - name: Enable Pull Request Automerge
              run: gh pr merge --merge --admin ${{ steps.cpr.outputs.pull-request-number }}
              env:
                GH_TOKEN: ${{ secrets.GH_PAT }}
```
  The trick was using 
`--admin ${{ steps.cpr.outputs.pull-request-number }}`
 instead of
 `--auto`

Here's my completed action.  https://github.com/Bearsampp/Bearsampp/blob/main/.github/workflows/combine_releases.yml
