### ISSUE TITLE
Error: Can't enable auto-merge for this pull request.

### ISSUE THREAD

**Issue by arunanandhan** [peter-evans/enable-pull-request-automerge#310]
I am getting this error - Can't enable auto-merge for this pull request.

Its merging to the protected branch (main). Should i need to update any branch protection settings?

Here is the code
```
      # Create Pull Request with the updated changes
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          branch: ${{ steps.application.outputs.application-names }}
          delete-branch: true
          labels: promotion
          title: "[Promotion] ${{ steps.application.outputs.application-names }}"

      # Enable Auto-merge option in the Pull Request
      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash

```
