### ISSUE TITLE
Error: Pull Request is not mergable

### ISSUE THREAD

**Issue by jcquiles** [peter-evans/enable-pull-request-automerge#311]
Hey @peter-evans im attempting to create a PR to merge a dev branch into a qa branch. However, seeing an error message when this runs on the **merge PR job** of the workflow. The error appears with the message **Error: Pull Request is not mergable.** 
```
Run juliangruber/merge-pull-request-action@v1
  with:
    github-token: ***
    number: 1
    method: merge
Error: Pull Request is not mergeable
```
Here is the particular part of the config being used in the yaml: 
      
```
      - name: create PR to deploy to QA
        uses: peter-evans/create-pull-request@v3
        with:
          branch: deploy-qa
          base: react-qa
          title: QA Deploy (${{ github.actor }})
          commit-message: create PR to deploy react-dev to react-qa
          body: Auto-generated PR (via Github Actions manual workflow) to deploy react-dev to react-qa. Intiated by ${{ github.actor }}.
          delete-branch: true
```
I have my theories on why this is not working, but was wondering if you have seen this particular appear or if you see something that should be improved in that particular part of the yaml. Any advice is appreciated. Thank you.
