### ISSUE TITLE
Error: Could not resolve to a PullRequest with the number of 0.

### ISSUE THREAD

**Issue by arunanandhan** [peter-evans/enable-pull-request-automerge#312]
I am getting this error (Error: Could not resolve to a PullRequest with the number of 0). Not sure what this mean. Can you explain why this error is happening? Can you help me out to fix this?

Here is my code
```
      # Create Pull Request with the updated changes
      - name: Create Pull Request
        if: steps.application.outputs.application-names != ''
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          body: |
            Automated promotion of the following applications: ${{ steps.application.outputs.application-names }}
            Revision: ${{ github.event.inputs.revision }}
          branch: ${{ steps.application.outputs.application-names }}
          delete-branch: true
          labels: promotion
          title: "[Promotion] ${{ matrix.service }}"

      # Enable Auto-merge option in the Pull Request
      - name: Enable Pull Request Automerge
        if: steps.application.outputs.auto-merge == 'true'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
```

The pull request also DID NOT get created.

![Capture](https://user-images.githubusercontent.com/48812131/157543681-4a843bc8-6f8c-470d-9b2f-1bdc17548f13.JPG)
