### ISSUE TITLE
Error: This endpoint requires you to be authenticated.

### ISSUE THREAD

**Issue by cherryleafroad** [peter-evans/enable-pull-request-automerge#331]
Not sure exactly what's going on, because I have this enabled on a different repo and it works perfectly (or did? Maybe something is wrong with Github at the moment)

Anyways, I have a secret token with `repo` privileges, it's all verified to be a valid token with correct privileges, the name is right, etc etc.

I'm using `peter-evans/enable-pull-request-automerge@v2`
I'm using the following, and the action does run, I know it gets the right PR number.
```yml
      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          # same token I'm using elsewhere, verified it works and is valid
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
```

In my repo settings, I have both `Automatically delete head branches` and `Allow auto-merge` enabled, and I have a branch protection rule enabled `Require a pull request before merging` and `Require approvals` (1), along with your example of auto approving it (though it never gets that far).

I'm certain I've checked off every box for this to work, and yet it seems github is refusing to work. Any ideas?

My guess is maybe github itself is broken, cause I used my secret token for the create pull request action, and it ALWAYS fails saying something like `fatal: could not read Username for 'https://github.com/': No such file or directory`, unless I let it use the default `GITHUB_TOKEN`. Creating a new secret token with the same privileges results in exactly the same errors

I think I'm at my wits end. Github seems to hate me :/

**Comment by peter-evans** [comment]
Hi @cherryleafroad 

It might be due to how the workflow is being triggered. Workflows triggered by a pull request from a fork don't have access to secrets. In that case the secret will be empty and result in the error you are seeing. There is some info about this here:
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks

If that doesn't explain your issue let me know.

**Comment by cherryleafroad** [comment]
That's the strange thing in fact; it's an ordinary push workflow which is definitely triggered on push.
```yml
on:
  push:
    branches: [ main ]
  workflow_dispatch:
```
