### ISSUE TITLE
A Personal Access Token is not actually required. A GITHUB_TOKEN will work

### ISSUE THREAD

**Issue by grintor** [peter-evans/enable-pull-request-automerge#342]
Hey,

First of all, thank you for making this Action, it's really helpful.

I wanted to point out that your readme says using a GITHUB_TOKEN will not work when in fact it can.

I had been struggling for days to figure out how to create an action that would auto-merge pull request from approved bots (or any approved user) to a protected branch after passing checks, but would NOT approve requests from *just anybody*. The question of how to auto-merge dependabot pull requests is a popular one. I ended up pulling it off with this workflow (Which as you can see does not use a PAT):

```yaml
name: automerge
on:
  pull_request_target:
jobs:
  automerge:
    runs-on: ubuntu-latest
    env:
      # append additional users below to allow automerge for them
      USER_ALLOWLIST: |
        '[
          "${{github.repository_owner}}",
          "dependabot[bot]"
        ]'
    steps:

      - name: print troubleshooting info
        run: |
          echo "event name:" ${{github.event_name}}
          echo "event action:" ${{github.event.action}}
          echo "actor:" ${{github.actor}}
          echo "repository owner:" ${{github.repository_owner}}
          echo "pull request user:" ${{github.event.pull_request.user.login}}
          echo "pull request number:" ${{github.event.pull_request.number}}
          echo "allow list:" ${{ env.USER_ALLOWLIST }}
          echo "actor approved?": ${{contains(fromJSON(env.USER_ALLOWLIST), github.actor)}}
          echo "pull request user approved?": ${{contains(fromJSON(env.USER_ALLOWLIST), github.event.pull_request.user.login)}}

      - name: automerge
        if: >-
          ${{
            contains(fromJSON(env.USER_ALLOWLIST), github.actor) &&
            contains(fromJSON(env.USER_ALLOWLIST), github.event.pull_request.user.login)
          }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          pull-request-number: ${{github.event.pull_request.number}}
          merge-method: squash
````

The trick here is to use the "pull_request_target" event instead of the "pull_request" event. The GITHUB_TOKEN from a pull_request event does not have the required permissions because it runs in the security context of the requestor. On the other hand, the pull_request_target event is identical to the pull_request event in every way except that the GITHUB_TOKEN runs in the security context of the "target" (the approver).

Obviously then pull_request_target can be dangerous because it can allow anyone from the general public full write access to the repo by combining it with enable-pull-request-automerge. You can see that my approach to secure the workflow above is to build an allow list.

Anyway, I just wanted to share this with you because I was pretty excited to finally get it working and not having to use PAT. Feel free to share my workflow above as an example in your readme. I suspect a lot of people who are looking for a way to automerge dependabot and other bots wind up here.
