### ISSUE TITLE
Pull request is in unstable status

### ISSUE THREAD

**Issue by izavads** [peter-evans/enable-pull-request-automerge#355]
Hi , 
getting the below message when trying to use the action : 

Request failed due to following response errors: - ["Pull request Pull request is in unstable status"]

```
      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.MERGE_SECRET }}
          pull-request-number: ${{ github.event.number }}
          merge-method: squash
```
