### ISSUE TITLE
Option for disabling automerge

### ISSUE THREAD

**Issue by alfieyfc** [peter-evans/enable-pull-request-automerge#74]
This could be totally up to another action project, but still posting here for now just to raise the idea, _though I don't know if it's implementable_.

I'm proposing adding an input such as `mode`, which is default to `enable`, and ignores the `merge-method` input when set to `disable`. The purpose is to allow this action to disable automerge in desired conditions. An example scenario would be something like below, triggered when the base of PR is edited (I bet there's a better way to trigger this).

```yaml
name: PR Edited
on:
  pull_request:
    types: [edited]
jobs:
  enable-automerge:
    if: ${{ github.event.pull_request.base.ref != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.MY_PAT }}
          pull-request-number: ${{ github.event.pull_request.number }}
  disable-automerge:
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.MY_PAT }}
          pull-request-number: ${{ github.event.pull_request.number }}
          mode: disable
```

I'm struggling with finding another action that disables automerge in marketplace and thought it would be nice if this action has such addition.
