### ISSUE TITLE
Don't fail for 0th PR

### ISSUE THREAD

**Issue by lukasz-mitka** [peter-evans/enable-pull-request-automerge#88]
I'm using `cron` to update dependencies. Sometimes it produces no change and makes `peter-evans/enable-pull-request-automerge` fail.
It's possible to add `if` condition, but I guess it would be nicer to just ignore such error.

I propose that `peter-evans/enable-pull-request-automerge` ignores `pull-request-number: 0` instead of failing

```
on:
  schedule:
    - cron: '0 0 * * *'
# ...
      - uses: actions/checkout@v2

      # update dependencies

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
```

**Comment by peter-evans** [comment]
Hi @lukasz-mitka 

You're right, that is a case that I overlooked in the readme example. However, I would like to suggest using an `if` condition rather than changing the action to ignore `0`. Doing that in the action feels a bit "hidden" and I think it would be more readable/understandable to explicitly define the condition in the workflow.

I will update the readme example to this:
```yml
      - uses: actions/checkout@v2

      # Make changes to pull request here

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
```
