### ISSUE TITLE
Alternative to approve pull request action

### ISSUE THREAD

**Issue by epassaro** [peter-evans/enable-pull-request-automerge#993]
I was looking to an alternative for juliangruber/approve-pull-request-action and I thought it could be useful for someone else:

```
      - name: Approve pull request
        run: gh pr review ${{ steps.create-pr.outputs.pull-request-number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.AUTHORIZED_TOKEN }}
        if: steps.create-pr.outputs.pull-request-operation == 'created'
```
